regexes = [
	(r'#.*#$','TK_CMNT'),
	(r'\$[a-z0-9_]+','TK_IDTFR'),
	(r'[a-z0-9_]+\(\)','TK_FUNC_IDTFR'),  
	(r'[a-z0-9_]+\(\$[a-z0-9_]+\)','TK_FUNC_IDTFR'),	
	('[0-9]+\.[0-9][0-9]','TK_CONST_RLNUM'),
	(r'\d+','TK_CONST_NUM'),
	(r'\'.*\'','TK_CONST_STRING'),
	(r'[a-z0-9_]+','TK_CONST_STRING'),
	(r'[0-9][0-9]:[0-9][0-9]','TK_CONST_TIME'),
	(r'\(','TK_OB'),
	(r'\)','TK_CB'),
	(r'\.','TK_PRD'), 
	(r':','TK_CLN'),
	(r'\+','TK_PLUS'),
	(r'\-','TK_MINUS'),
	(r'\*','TK_MUL'),
	(r'/','TK_DIV'),
	(r'%','TK_MOD'),
	(r',','TK_COMMA'),
	(r';','TK_SCLN'),
	(r'=','TK_ASSGN'),
	('AND','TK_AND'),		#missing keyword
	('OR','TK_OR'),			#missing keyword
	('DISTANCE','TK_DIST'),
	('TIME','TK_TIME'),
	('NAVIGATOR','TK_NAV'),
	('FUNC','TK_FUNC'),
	('ENDFUNC','TK_ENDFUNC'),
	('RUN','TK_RUN'),
	('REPEAT','TK_REPEAT'),
	('ENDREPEAT','TK_ENDREPEAT'),
	('IF','TK_IF'),
	('ENDIF','TK_ENDIF'),
	('EQUALS','TK_EQUALS'),
	('GREATERTHAN','TK_GT'),
	('NOTGREATERTHAN','TK_NGT'),
	('LESSTHAN','TK_LT'),
	('NOTLESSTHAN','TK_NLT'),
	('ESCAPE','TK_ESC'),
	('DEFINE','TK_DEFINE'),
	('NOTEQUALS','TK_NEQUALS'),
	('AS','TK_AS'),
	('RETURN','TK_RETURN'),
	(r'GETREADING\(\)','TK_GETRDNG'),
	('SENSOR','TK_SENSOR'),
	('OUTLIGHTS','TK_OLITS'),
	('OUTCOOLANT','TK_OCLNT'),
	('OUTWIPERS','TK_OWPRS'),
	('OUT','TK_OUT'),
	('FUELLEVEL|FuelLevel','TK_FL'),
	('GEAR|Gear','TK_GEAR'),
	('SPEED|Speed','TK_SPEED'),
	('ODOMETER|Odometer','TK_ODO'),
	('HUMIDITY|Humidity','TK_HUM'),
	('ENGINETEMP|Enginetemp','TK_ENGTEMP'),
	('LUIMNOSITY|Luminosity','TK_LUM'),
	('GET','TK_GET'),
	('FROM','TK_FROM'),
	('CLOSEST','TK_CLOSEST'),
	('Oxygen','TK_OXY'),		#missing keyword
	('Throttle','TK_THR'),		#missing keyword 
	('Torque','TK_TOR'),		#missing keyword 
	('Brakepressure','TK_BP'),	#missing keyword
	('Enginestatus','TK_ENGSTAT'),
	
	
	
			]